services:
  - type: web
    name: big-ten-sports
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

staticSites:
  - name: r2r2r-companion
    buildCommand: cd r2r2r-app && npm install --legacy-peer-deps && EXPO_NO_TELEMETRY=1 CI=1 npx expo export --platform web && cp public/_redirects dist/_redirects
    staticPublishPath: r2r2r-app/dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
